general:
  data_base_dir: /app/data
  version: 1.0
  description: run sybil pipeline

execute:
- DicomImporter
- SybilRunner
- ReportExporter
- DataOrganizer

modules:
  DicomImporter:
    meta: 
      mod: '%Modality'

  ReportExporter:
    format: compact
    includes:
      - data: sybilscores
        label: Sybil_Scores_6years
        value: value
  
  DataOrganizer:
    targets:
      - json:mod=report-->[i:sid]/sybil_scores_6years.json
